### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by thomwolf** [glample/fastBPE#11]
Adapting the number of threads (commit c520726) causes a compilation error on my Mac.
```
fast.cc:614:36: error: variable length array of non-POD element type 'unordered_map<string, string>' (aka 'unordered_map<basic_string<char, char_traits<char>, allocator<char> >, basic_string<char,
      char_traits<char>, allocator<char> > >')
  unordered_map<string, string> bpe[kThreads];
```

Reverting to a fixed number of threads (10) fixes it.

I use Apple LLVM version 8.0.0 (clang-800.0.42.1) (Target: x86_64-apple-darwin16.7.0)

**Comment by timlacroix** [comment]
Hi @thomwolf, thanks for noticing.
This issue doesn't appear for Apple LLVM version 10.0.1 so if you can upgrade, that's an option. Otherwise, your fix is fine and let's you adapt the number of threads to your needs :)
