### ISSUE TITLE
fast.cc: No such file or directory

### ISSUE THREAD

**Issue by miaodl** [glample/fastBPE#20]
sorry... this should be issue of microsoft/MASS

I am trying to run bash file "get-data-nmt.sh".

Compiling fastBPE...
g++: error: fast.cc: No such file or directory
g++: fatal error: no input file

it's like the installation of fastBPE has changed:

from:
g++ -std=c++11 -pthread -O3 fast.cc -o fast

to:
g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast

please take this into consideration.

**Comment by glample** [comment]
Yes, this change broke a few repos that were using fastBPE, sorry about that. We will keep the same installation command in the future.
