### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by matteosal** [glample/fastBPE#3]
Hello, as title says, what's the licensing for this code? Thanks!

**Comment by sbodenstein** [comment]
@timlacroix: We would love to use your library, but can't use it without clarification about the licensing. Any chance you could clarify it?

Thanks so much!

**Comment by timlacroix** [comment]
woopsy.
I added a non-commercial CC-BY-NC license file.
Sorry about this.

**Comment by sbodenstein** [comment]
Thanks!

**Comment by hglaude** [comment]
Hello,

Would you be willing to use a less restrictive license like MIT?

Thank you

**Comment by jwijffels** [comment]
I'd be also interested in such a less restrictive license. E.g. CC-BY-SA is just fine for me. If the license is changed, I'd be happy to make an R wrapper on this C++ library and put it on CRAN. Hope you can consider it.

**Comment by timlacroix** [comment]
MIT License it is then.

**Comment by jwijffels** [comment]
Many thanks! Appreciate this!
