### ISSUE TITLE
Learn bpe fails with `bad_alloc` even for relatively small datasets

### ISSUE THREAD

**Issue by mttk** [glample/fastBPE#4]
Hey,

`learnbpe` is failing on [this](https://github.com/glample/fastBPE/blob/master/fast.cc#L326) line if there's not enough available memory. I tried to run the script on my machine with 8G ram and it threw

```
Loading vocabulary from alice_in_wonderland.txt ...
Read 26443 words (5293 unique) from text file.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

Running the same on a server with ~512G doesn't fail. Is there any way of fixing this so bpe can be ran locally?

**Comment by rucha3** [comment]
@mttk How did you resolve this? I have the same issue.

**Comment by yukioichida** [comment]
Hi @mttk ,

I have this same problem. However, the file fast.cc is no longer in this repo. 

For anyone that has this same issue, just set a low value in the line: https://github.com/glample/fastBPE/blob/master/fastBPE/fastBPE.hpp#L28.

**Comment by tuanshanyou** [comment]
@yukioichida 
Thank you very much. The problem has been solved. You are wonderful
