### ISSUE TITLE
【vocab size】Is there another way to limit the vocab size?

### ISSUE THREAD

**Issue by imyzx2017** [glample/fastBPE#47]
The method you provide by constraining the codes size, like "./fast learnbpe 40000 train.de train.en > codes", just indirectly adjusted the size of vocab. 

My question are:
1. What is the relationship between the size of the codes and the size of the vocabulary, Any approximate function?
2. How can I limit the specific length of the vocabulary according to parameters settings？

Thanks！！

**Comment by Xingxl2studious** [comment]
Has the problem been solved? I had the same question.
