### ISSUE TITLE
Not able to understand the outputs of learnbpe

### ISSUE THREAD

**Issue by pranaymanocha** [glample/fastBPE#5]
Hi,
I was looking at the outputs of the learnbpe command. For example, I have a file in which I have the following characters
a b c d e f ab bc cd de ef
I try getvocab to get 11 characters (11 unique) which is understandable.
Then I try to do learnbpe with 11 ncodes on this file.
I get the following outputs:-
a b</w> 1
b c</w> 1
d e</w> 1
e f</w> 1
c d</w> 1
a b</w> 0
a b</w> 0
a b</w> 0
a b</w> 0
a b</w> 0
a b</w> 0
I am not able to understand what the output signifies.

Best,
Pranay

**Comment by glample** [comment]
Note that the vocabulary size and the number of codes is not the same thing. The codes are the merge operations that will be applied to your text. Each word is split at character level, and then all codes are applied to each word.

"ab" will become "a b" when you split it at character level, then if you apply the first BPE split on it (a b 1) it will merge it back to "ab". The digit on the right is the number of times an occurrence was observed when counting the character bigrams.

Maybe try with a small text, it will be simpler to understand on a concrete example what is going on.

**Comment by songtaoshi** [comment]
hi @glample really thank your work, but how to set the codes number according to my corpus?

**Comment by glample** [comment]
Hi,

40000 or 60000 is usually a good number. When we only work with English we use 40000, when we use 100 languages we use 200000 codes (but this is quite a lot). It also depends on the size of your corpus. If your corpus is really small, you may want to only use 20000 codes. There is no general rule about this. Best is to try a few values and quickly check what works best.
