### ISSUE TITLE
ReadCodes error on ec2 instance

### ISSUE THREAD

**Issue by rucha3** [glample/fastBPE#7]
I am using fastBPE as part of a larger pipeline. It works fine on my PC.
But when I run this using sagemaker on an instance, I get the following error:

> fast: fast.cc:464: void readCodes(const char*, std::unordered_map<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >, unsigned int, pair_hash>&, std::unordered_map<std::__cxx11::basic_string<char>, std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&): Assertion `codes.find(pair) == codes.end()' failed.

**Comment by kev123456** [comment]
Delete extra “o o 0” line in codes files.

**Comment by zhishui3** [comment]
> Delete extra “o o 0” line in codes files.

Sorry, there is still the same mistake.

**Comment by zhishui3** [comment]
> Delete extra “o o 0” line in codes files.

Sorry, there is still the same mistake.
what should I do?

**Comment by Tikquuss** [comment]
if nCodes is wrongly chosen there will be errors when 'applybpe'.  How to choose this number? What exactly is it used for? I don't know. But lowering it solves the problem (choose a low value to see).
